theme: jekyll-theme-merlot
title: Welcome to JargonautStudios Space Shooter Tutorial!
description: This project is based on the Unity Technologies tutorial seen here 'https://unity3d.com/learn/tutorials/s/space-shooter-tutorial'
